version: '3.9'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lit-go-sdk-dev
    image: lit-go-sdk
    environment:
      ENV: development
      LIT_VERSION: '1.1.228'
    volumes:
      - '.:/go/src'
      - './.cache:/tmp/cache'
