name: Run tests and security checks

on:
  push:
    branches-ignore:
      - main

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run security tests
        run: PATH=$PATH:$HOME/go/bin make security
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
